# Generated by Django 5.1.7 on 2025-06-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeOvertime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('hours_worked', models.FloatField()),
                ('regular_hours', models.FloatField(default=8.0)),
                ('overtime_hours', models.FloatField()),
            ],
        ),
    ]
